### ISSUE TITLE
Damage: Add SA-5 missile.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/flightgear-saab-ja-37-viggen#180]
Right now the SA-5 doesn't deal damage nor warnings to the Viggen

**Comment by SammySkycrafts** [comment]
SA-5 system is correctly implemented in the Viggen (Both damage and RWR) - issue being faced here appears to be due to the fact the viggen's mp-visibility-range being set to the default of 100 miles, so any hits at a distance greater of that will not cause damage, cause RWR spike, or Missile warnings. (Just tested, as soon as the hello message appeared, RWR worked as normal..)

I'd recommend a MP distance of 200 miles, exceeding the maximum range of the S-200, and allowing some flexibility for future expansion.

**Comment by colingeniet** [comment]
Okay, I didn't realise the S-200 range was that crazy.
I will increase the MP and RWR ranges. And the latter should probably
be made dependent on radar type at this point.

**Comment by colingeniet** [comment]
Fixed by d97c3a56 and eeb8dace
