### ISSUE TITLE
Scale instead of select animations

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#82]
In the main aircraft model, most `select` animations are replaced with `scale` animations which scale down to 0. According to this commit https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/commit/fa6219e27310f78209f39e83c74592d9ed9b07d2, it was for performance reasons. However, I am not sure that it is still relevant, the F16 for instance has plenty of similar `select` animations.

Is there a reason to keep them ? If not do you mind if I change everything back to `select` so as to simplify the code ?

**Comment by NikolaiVChr** [comment]
Hmm, when I did that commit and similar commits, I had a very slow "AMD Phenom I Quad with GF-550Ti" and I could feel the difference. I did some tests and it was clear that select animations were significant part of the stutters, and maybe part of stutters in MP when people flew close to a Viggen.

Thing is, I no longer have a slow PC, so I cannot do any tests to see if the issue is still there for people with slower PCs.

But I agree that its an ugly hack to use scale animations.

I haven't had any stutters in F-16 like the ones I had in the Viggen. And yes it has plenty of select animations.

I guess if those scale animations bother you, you can replace them. Its fine.

**Comment by colingeniet** [comment]
The issue I had is that writing backward compatible MP code like [that](https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/blob/41ad5ea7b0b09f7cb3f621e07e768c8e9f9b9eb1/Aircraft/JA37/Models/Effects/proc-als-lights/landing-light.xml) is quite annoying with scale animations.

In the end, I only changed animations corresponding to wing and canopy damage in https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/pull/87. In particular, scale is still used for the landing gears.

**Comment by NikolaiVChr** [comment]
In Old days I used to be very strict with having it be backwards compatible.

But not anymore. I just change what needs to be changed, and its up to the pilots to get a recent version to fly so everything works.
